title: Zenova Centre
description: Zenova 的文件中心
remote_theme: just-the-docs/just-the-docs

url: https://zenova-com-tw.github.io/docs

# Mermaid 支援
mermaid:
  version: "10.9.0"

# Just the Docs 自訂設定
just_the_docs:
  search_enabled: true
  show_sidebar: true
  collections:
    docs:
      output: true
      permalink: /:collection/:path/