title: Zenova Centre
description: Zenova 的文件中心
remote_theme: just-the-docs/just-the-docs

url: https://zenova-com-tw.github.io/docs

# 開啟搜尋
just_the_docs:
  search_enabled: true
  show_sidebar: true
  mermaid:
    enabled: true
  collections:
    docs:
      output: true
      permalink: /:collection/:path/
      